# Generated by Django 4.2.4 on 2023-08-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Placed', max_length=20),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizzabase'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.cheese'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza_app.topping'),
        ),
    ]
