# Generated by Django 4.2.4 on 2023-08-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_cheese_pizzabase_topping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='In Progress', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='base',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='base',
            field=models.CharField(choices=[('thin-crust', 'Thin Crust'), ('normal', 'Normal'), ('cheese-burst', 'Cheese Burst')], default='normal', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='cheese',
            field=models.CharField(choices=[('mozarella', 'Mozarella'), ('cheddar', 'Cheddar'), ('parmesan', 'Parmesan'), ('gouda', 'Gouda')], default='mozarella', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='topping_orders', to='pizza_app.pizza'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='Default Pizza Name', max_length=255),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='PizzaBase',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.order'),
        ),
    ]
