# Generated by Django 4.2.4 on 2023-08-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_orderstatus_remove_order_pizzas_remove_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizza_app.order'),
        ),
    ]
