# Generated by Django 4.2.4 on 2023-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_remove_pizza_order_order_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='topping_orders', to='pizza_app.pizza'),
        ),
    ]
