# Generated by Django 4.2.4 on 2023-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='topping_orders', to='pizza_app.pizza'),
        ),
    ]
