# Generated by Django 4.2.4 on 2023-08-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_alter_order_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
    ]
