# Generated by Django 4.2.4 on 2023-08-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0009_remove_order_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
