# Generated by Django 4.2.4 on 2023-08-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0011_order_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Price',
        ),
    ]
