# Generated by Django 4.2.4 on 2023-08-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0013_alter_price_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
